### ISSUE TITLE
Add a way to control what Node version is used in our project

### ISSUE THREAD

**Issue by MtuMartian** [3Ustin/spotify_web_client#2]
This can be done using nvm (Node Version Manager)

Developers should install nvm globally and we should add a .nvmrc file to our project
https://github.com/nvm-sh/nvm#nvmrc

We can use the current LTS version of Node which can be found here https://nodejs.org/en/

**Comment by 3Ustin** [comment]
Making the .nvmrc file makes sense, but getting the the Node Version Manager through git is somehow confusing me. I'll @ you on discord.

**Comment by 3Ustin** [comment]
Making a comment in the README file for future developers would be helpful here.

**Comment by 3Ustin** [comment]
Made a comment in the README file

**Comment by 3Ustin** [comment]
Finished creating .nvmrc file. The results may vary, but done correctly.
