### ISSUE TITLE
Add Web Playback

### ISSUE THREAD

**Issue by MtuMartian** [3Ustin/spotify_web_client#5]
https://developer.spotify.com/documentation/web-playback-sdk/quick-start/

We will use the Spotify Web Playback SDK to play audio in our application. Spotify provides a getting started guide that shows how to create a simple application using JavaScript that acts as a web player. We should follow this guide and use it to add web playback to our React application

Since the guide is written using just JavaScript it may be easier to follow the guide exactly and then once it's working using their guide, add it to our React app

**Comment by 3Ustin** [comment]
To complete this issue read all eight of these points 
- https://reactjs.org/docs/hooks-intro.html
To continue follow this guide and take note of how the SDK is being put on the DOM.
- https://developer.spotify.com/documentation/web-playback-sdk/guide/#webplayback-component

**Comment by 3Ustin** [comment]
closed by #12 which generates 71cbc68822b0c874f06b2f96a7f45f700d031cfa
