### ISSUE TITLE
Add data about current song to player

### ISSUE THREAD

**Issue by MtuMartian** [3Ustin/spotify_web_client#6]
Once we have web playback complete, we may want to know what song is currently playing in our UI.
This data can be fetched from the WebPlayback SDK getCurrentState method
https://developer.spotify.com/documentation/web-playback-sdk/reference/

This issue will be complete when our application displays the current song title, album title, and artist. If there is no current song, display a message saying no song is currently playing

**Comment by 3Ustin** [comment]
This Pull request solve issue #6
